/*
  # Add Paper Reviews Table

  Creates a dedicated table for storing paper reviews generated by the
  multi-agent review system. This is separate from paper_analysis to
  store the more comprehensive review data including:
  - Conference-style reviews
  - Graph data for visualization
  - Lineage relationships
  - Processing metadata
*/

-- Create paper_reviews table
CREATE TABLE IF NOT EXISTS paper_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  paper_id uuid REFERENCES papers(id) ON DELETE CASCADE NOT NULL,
  community_id uuid REFERENCES communities(id) ON DELETE SET NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Review data (stored as JSONB for flexibility)
  review_data jsonb,
  graph_data jsonb,
  lineage_data jsonb,

  -- Metadata
  processing_time_seconds float,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_paper_reviews_paper_id ON paper_reviews(paper_id);
CREATE INDEX IF NOT EXISTS idx_paper_reviews_community_id ON paper_reviews(community_id);
CREATE INDEX IF NOT EXISTS idx_paper_reviews_created_by ON paper_reviews(created_by);
CREATE INDEX IF NOT EXISTS idx_paper_reviews_created_at ON paper_reviews(created_at DESC);

-- Enable RLS
ALTER TABLE paper_reviews ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view reviews in their communities
CREATE POLICY "Users can view reviews in their communities"
  ON paper_reviews
  FOR SELECT
  TO authenticated
  USING (
    community_id IS NULL
    OR community_id IN (
      SELECT community_id FROM community_members
      WHERE user_id = auth.uid()
    )
  );

-- Policy: Users can create reviews
CREATE POLICY "Users can create reviews"
  ON paper_reviews
  FOR INSERT
  TO authenticated
  WITH CHECK (created_by = auth.uid() OR created_by IS NULL);

-- Policy: Users can update their own reviews
CREATE POLICY "Users can update own reviews"
  ON paper_reviews
  FOR UPDATE
  TO authenticated
  USING (created_by = auth.uid() OR created_by IS NULL);

-- Policy: Service role can do everything
CREATE POLICY "Service role full access"
  ON paper_reviews
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_paper_reviews_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_paper_reviews_updated_at
  BEFORE UPDATE ON paper_reviews
  FOR EACH ROW
  EXECUTE FUNCTION update_paper_reviews_updated_at();

-- Comments
COMMENT ON TABLE paper_reviews IS 'Stores comprehensive paper reviews from multi-agent review system';
COMMENT ON COLUMN paper_reviews.review_data IS 'Contains conference_review, deep_analysis, contributions, reproducibility, summary, literature';
COMMENT ON COLUMN paper_reviews.graph_data IS 'Knowledge graph nodes and edges for visualization';
COMMENT ON COLUMN paper_reviews.lineage_data IS 'Extracted paper-to-paper relationships';
