"""
Paper Mind Graph - Data Models & Schema
========================================
Defines the node types, edge types, and data structures for the paper mind graph.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Literal
from enum import Enum
import json
from datetime import datetime
import uuid


# ============================================================================
# Node Types
# ============================================================================

class NodeType(str, Enum):
    """Types of nodes in the mind graph."""
    PAPER = "paper"           # Root node
    SECTION = "section"       # Paper sections/subsections
    CONCEPT = "concept"       # Key ideas, definitions
    METHOD = "method"         # Algorithms, architectures
    EXPERIMENT = "experiment" # Experimental setup/results
    FIGURE = "figure"         # Figures with captions
    TABLE = "table"           # Tables with captions
    EQUATION = "equation"     # Mathematical equations
    DATASET = "dataset"       # Datasets mentioned
    TASK = "task"             # Tasks/benchmarks
    RESULT = "result"         # Specific results/findings
    LIMITATION = "limitation" # Limitations mentioned
    FUTURE_WORK = "future_work"  # Future directions
    REFERENCE = "reference"   # Cited papers


class EdgeType(str, Enum):
    """Types of edges in the mind graph."""
    # Structural edges
    HAS_SECTION = "has_section"
    HAS_SUBSECTION = "has_subsection"
    
    # Content edges
    DEFINES = "defines"           # Section/Chunk defines Concept
    USES_METHOD = "uses_method"   # Experiment uses Method
    PROPOSES = "proposes"         # Paper/Section proposes Method
    EVALUATES_ON = "evaluates_on" # Experiment evaluates on Dataset/Task
    
    # Visual/Reference edges
    ILLUSTRATED_BY = "illustrated_by"  # Concept/Method → Figure
    SUMMARIZED_BY = "summarized_by"    # Results → Table
    DERIVED_BY = "derived_by"          # Concept → Equation
    
    # Semantic edges
    DEPENDS_ON = "depends_on"     # Concept depends on Concept
    EXTENDS = "extends"           # Method extends another Method
    COMPARES_TO = "compares_to"   # Experiment compares to baseline
    SUPPORTS = "supports"         # Result supports Concept
    CONTRADICTS = "contradicts"   # Result contradicts prior work
    CITES = "cites"               # Paper cites Reference
    
    # Relationship edges
    RELATED_TO = "related_to"     # General relationship
    PART_OF = "part_of"           # Component relationship


class VerificationStatus(str, Enum):
    """Verification status of nodes/edges."""
    AUTO_GENERATED = "auto"      # Generated by LLM
    HUMAN_VERIFIED = "verified"  # Human approved
    HUMAN_EDITED = "edited"      # Human modified
    FLAGGED = "flagged"          # Needs review


# ============================================================================
# Core Data Classes
# ============================================================================

@dataclass
class SourceLocation:
    """Location in the original PDF."""
    page: int
    bbox: Optional[tuple] = None  # (x0, y0, x1, y1)
    line_start: Optional[int] = None
    line_end: Optional[int] = None
    char_start: Optional[int] = None
    char_end: Optional[int] = None
    
    def to_dict(self) -> Dict:
        return {
            "page": self.page,
            "bbox": self.bbox,
            "line_start": self.line_start,
            "line_end": self.line_end,
            "char_start": self.char_start,
            "char_end": self.char_end
        }
    
    @classmethod
    def from_dict(cls, d: Dict) -> 'SourceLocation':
        return cls(**d)


@dataclass
class Chunk:
    """A semantic chunk of the paper."""
    id: str
    text: str
    source_type: Literal["body", "figure", "table", "equation", "caption", "abstract"]
    section_id: Optional[str] = None
    page_span: tuple = (0, 0)
    source_locations: List[SourceLocation] = field(default_factory=list)
    embedding: Optional[List[float]] = None
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "text": self.text,
            "source_type": self.source_type,
            "section_id": self.section_id,
            "page_span": self.page_span,
            "source_locations": [loc.to_dict() for loc in self.source_locations]
        }


@dataclass
class GraphNode:
    """A node in the mind graph."""
    id: str
    type: NodeType
    title: str
    description: str = ""
    
    # Source tracking
    source_chunks: List[str] = field(default_factory=list)  # Chunk IDs
    origin_pages: List[int] = field(default_factory=list)
    source_locations: List[SourceLocation] = field(default_factory=list)
    
    # For figures/tables
    label: Optional[str] = None  # "Figure 3", "Table 1"
    caption: Optional[str] = None
    image_path: Optional[str] = None
    
    # For equations
    latex: Optional[str] = None
    equation_number: Optional[str] = None
    
    # Metadata
    verification_status: VerificationStatus = VerificationStatus.AUTO_GENERATED
    confidence: float = 1.0
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    modified_at: Optional[str] = None
    modified_by: Optional[str] = None  # "auto" or user ID
    
    # Additional properties
    properties: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "type": self.type.value,
            "title": self.title,
            "description": self.description,
            "source_chunks": self.source_chunks,
            "origin_pages": self.origin_pages,
            "source_locations": [loc.to_dict() for loc in self.source_locations],
            "label": self.label,
            "caption": self.caption,
            "image_path": self.image_path,
            "latex": self.latex,
            "equation_number": self.equation_number,
            "verification_status": self.verification_status.value,
            "confidence": self.confidence,
            "created_at": self.created_at,
            "modified_at": self.modified_at,
            "modified_by": self.modified_by,
            "properties": self.properties
        }
    
    @classmethod
    def from_dict(cls, d: Dict) -> 'GraphNode':
        d = d.copy()
        d["type"] = NodeType(d["type"])
        d["verification_status"] = VerificationStatus(d.get("verification_status", "auto"))
        d["source_locations"] = [SourceLocation.from_dict(loc) for loc in d.get("source_locations", [])]
        return cls(**d)


@dataclass
class GraphEdge:
    """An edge in the mind graph."""
    id: str
    type: EdgeType
    source_id: str  # Source node ID
    target_id: str  # Target node ID
    
    # Edge metadata
    label: Optional[str] = None  # Optional label/description
    reason: Optional[str] = None  # Why this edge exists
    weight: float = 1.0
    
    # Source tracking
    source_chunks: List[str] = field(default_factory=list)
    
    # Verification
    verification_status: VerificationStatus = VerificationStatus.AUTO_GENERATED
    confidence: float = 1.0
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "type": self.type.value,
            "source_id": self.source_id,
            "target_id": self.target_id,
            "label": self.label,
            "reason": self.reason,
            "weight": self.weight,
            "source_chunks": self.source_chunks,
            "verification_status": self.verification_status.value,
            "confidence": self.confidence,
            "created_at": self.created_at
        }
    
    @classmethod
    def from_dict(cls, d: Dict) -> 'GraphEdge':
        d = d.copy()
        d["type"] = EdgeType(d["type"])
        d["verification_status"] = VerificationStatus(d.get("verification_status", "auto"))
        return cls(**d)


# ============================================================================
# Paper Structure Classes
# ============================================================================

@dataclass
class PaperMetadata:
    """Metadata extracted from the paper."""
    title: str = ""
    authors: List[str] = field(default_factory=list)
    abstract: str = ""
    venue: str = ""
    year: str = ""
    arxiv_id: str = ""
    doi: str = ""
    keywords: List[str] = field(default_factory=list)
    num_pages: int = 0
    
    def to_dict(self) -> Dict:
        return {
            "title": self.title,
            "authors": self.authors,
            "abstract": self.abstract,
            "venue": self.venue,
            "year": self.year,
            "arxiv_id": self.arxiv_id,
            "doi": self.doi,
            "keywords": self.keywords,
            "num_pages": self.num_pages
        }


@dataclass
class Section:
    """A section of the paper."""
    id: str
    title: str
    level: int  # 1 = top level, 2 = subsection, etc.
    text: str
    page_span: tuple = (0, 0)
    parent_id: Optional[str] = None
    children_ids: List[str] = field(default_factory=list)
    source_locations: List[SourceLocation] = field(default_factory=list)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "title": self.title,
            "level": self.level,
            "text": self.text,
            "page_span": self.page_span,
            "parent_id": self.parent_id,
            "children_ids": self.children_ids,
            "source_locations": [loc.to_dict() for loc in self.source_locations]
        }


@dataclass 
class Figure:
    """A figure in the paper."""
    id: str
    label: str  # "Figure 3"
    caption: str
    page: int
    bbox: Optional[tuple] = None
    image_path: Optional[str] = None
    nearby_text: str = ""
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "label": self.label,
            "caption": self.caption,
            "page": self.page,
            "bbox": self.bbox,
            "image_path": self.image_path,
            "nearby_text": self.nearby_text
        }


@dataclass
class Table:
    """A table in the paper."""
    id: str
    label: str  # "Table 1"
    caption: str
    page: int
    content: str = ""  # Extracted table content
    bbox: Optional[tuple] = None
    nearby_text: str = ""
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "label": self.label,
            "caption": self.caption,
            "page": self.page,
            "content": self.content,
            "bbox": self.bbox,
            "nearby_text": self.nearby_text
        }


@dataclass
class Equation:
    """An equation in the paper."""
    id: str
    latex: str
    equation_number: Optional[str] = None
    page: int = 0
    context: str = ""  # Surrounding text
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "latex": self.latex,
            "equation_number": self.equation_number,
            "page": self.page,
            "context": self.context
        }


# ============================================================================
# Mind Graph Container
# ============================================================================

@dataclass
class MindGraph:
    """The complete mind graph for a paper."""
    paper_id: str
    metadata: PaperMetadata
    
    # Parsed structure
    sections: List[Section] = field(default_factory=list)
    figures: List[Figure] = field(default_factory=list)
    tables: List[Table] = field(default_factory=list)
    equations: List[Equation] = field(default_factory=list)
    
    # Chunks for retrieval
    chunks: List[Chunk] = field(default_factory=list)
    
    # Graph structure
    nodes: Dict[str, GraphNode] = field(default_factory=dict)
    edges: Dict[str, GraphEdge] = field(default_factory=dict)
    
    # Metadata
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    modified_at: Optional[str] = None
    version: str = "1.0"
    
    def add_node(self, node: GraphNode) -> str:
        """Add a node to the graph."""
        self.nodes[node.id] = node
        self.modified_at = datetime.now().isoformat()
        return node.id
    
    def add_edge(self, edge: GraphEdge) -> str:
        """Add an edge to the graph."""
        self.edges[edge.id] = edge
        self.modified_at = datetime.now().isoformat()
        return edge.id
    
    def get_node(self, node_id: str) -> Optional[GraphNode]:
        """Get a node by ID."""
        return self.nodes.get(node_id)
    
    def get_edges_from(self, node_id: str) -> List[GraphEdge]:
        """Get all edges originating from a node."""
        return [e for e in self.edges.values() if e.source_id == node_id]
    
    def get_edges_to(self, node_id: str) -> List[GraphEdge]:
        """Get all edges pointing to a node."""
        return [e for e in self.edges.values() if e.target_id == node_id]
    
    def get_neighbors(self, node_id: str, hops: int = 1) -> Dict[str, GraphNode]:
        """Get neighboring nodes within n hops."""
        visited = {node_id}
        current_level = {node_id}
        
        for _ in range(hops):
            next_level = set()
            for nid in current_level:
                # Get connected nodes
                for edge in self.get_edges_from(nid):
                    if edge.target_id not in visited:
                        next_level.add(edge.target_id)
                for edge in self.get_edges_to(nid):
                    if edge.source_id not in visited:
                        next_level.add(edge.source_id)
            visited.update(next_level)
            current_level = next_level
        
        return {nid: self.nodes[nid] for nid in visited if nid in self.nodes}
    
    def get_nodes_by_type(self, node_type: NodeType) -> List[GraphNode]:
        """Get all nodes of a specific type."""
        return [n for n in self.nodes.values() if n.type == node_type]
    
    def get_subgraph(self, node_ids: List[str]) -> 'MindGraph':
        """Get a subgraph containing only specified nodes and their edges."""
        subgraph = MindGraph(
            paper_id=self.paper_id,
            metadata=self.metadata
        )
        
        node_set = set(node_ids)
        for nid in node_ids:
            if nid in self.nodes:
                subgraph.nodes[nid] = self.nodes[nid]
        
        for edge in self.edges.values():
            if edge.source_id in node_set and edge.target_id in node_set:
                subgraph.edges[edge.id] = edge
        
        return subgraph
    
    def to_dict(self) -> Dict:
        """Convert to dictionary for serialization."""
        return {
            "paper_id": self.paper_id,
            "metadata": self.metadata.to_dict(),
            "sections": [s.to_dict() for s in self.sections],
            "figures": [f.to_dict() for f in self.figures],
            "tables": [t.to_dict() for t in self.tables],
            "equations": [e.to_dict() for e in self.equations],
            "chunks": [c.to_dict() for c in self.chunks],
            "nodes": {k: v.to_dict() for k, v in self.nodes.items()},
            "edges": {k: v.to_dict() for k, v in self.edges.items()},
            "created_at": self.created_at,
            "modified_at": self.modified_at,
            "version": self.version
        }
    
    def to_json(self, indent: int = 2) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)
    
    @classmethod
    def from_dict(cls, d: Dict) -> 'MindGraph':
        """Create from dictionary."""
        graph = cls(
            paper_id=d["paper_id"],
            metadata=PaperMetadata(**d["metadata"])
        )
        # Load sections, figures, etc.
        graph.sections = [Section(**s) for s in d.get("sections", [])]
        graph.figures = [Figure(**f) for f in d.get("figures", [])]
        graph.tables = [Table(**t) for t in d.get("tables", [])]
        graph.equations = [Equation(**e) for e in d.get("equations", [])]
        
        # Load chunks
        for c in d.get("chunks", []):
            chunk = Chunk(
                id=c["id"],
                text=c["text"],
                source_type=c["source_type"],
                section_id=c.get("section_id"),
                page_span=tuple(c.get("page_span", (0, 0)))
            )
            graph.chunks.append(chunk)
        
        # Load nodes and edges
        for k, v in d.get("nodes", {}).items():
            graph.nodes[k] = GraphNode.from_dict(v)
        for k, v in d.get("edges", {}).items():
            graph.edges[k] = GraphEdge.from_dict(v)
        
        graph.created_at = d.get("created_at", graph.created_at)
        graph.modified_at = d.get("modified_at")
        graph.version = d.get("version", "1.0")
        
        return graph


# ============================================================================
# Helper Functions
# ============================================================================

def generate_id(prefix: str = "") -> str:
    """Generate a unique ID."""
    short_uuid = str(uuid.uuid4())[:8]
    if prefix:
        return f"{prefix}_{short_uuid}"
    return short_uuid


def create_edge(
    edge_type: EdgeType,
    source_id: str,
    target_id: str,
    reason: str = None,
    source_chunks: List[str] = None
) -> GraphEdge:
    """Helper to create an edge."""
    return GraphEdge(
        id=generate_id("edge"),
        type=edge_type,
        source_id=source_id,
        target_id=target_id,
        reason=reason,
        source_chunks=source_chunks or []
    )


def create_node(
    node_type: NodeType,
    title: str,
    description: str = "",
    source_chunks: List[str] = None,
    origin_pages: List[int] = None,
    **kwargs
) -> GraphNode:
    """Helper to create a node."""
    prefix = node_type.value
    return GraphNode(
        id=generate_id(prefix),
        type=node_type,
        title=title,
        description=description,
        source_chunks=source_chunks or [],
        origin_pages=origin_pages or [],
        **kwargs
    )
